### ISSUE TITLE
(DH repost from Labora Issues) Create an Action Plan for Collegeville 2020 from collected best practices

### ISSUE THREAD

**Issue by amoralesg001** [Collegeville/VirtualTeams#11]
DH:
" @amoralesg001 ,@elaineraybourn, Let's use this issue as an aggregator for other issues and resources we are discovering for best practices in virtual meetings, to apply to Collegeville 2020."

DH: " #10 provides access the the FABRIC Workshop Remote Meeting guidance. We will benefit a lot from the advice the report provides."

**Comment by amoralesg001** [comment]
Would we still need this as an aggregator for other issues relevant towards this topic? We could also use the "Virtual Conference" label for information that deals with this topic as a way to gather all of our information.

**Comment by maherou** [comment]
I think we can leave this issue on Labora and close this instance of it.  Since the purpose of this issue is focused on our work (Labora, ha, ha), it doesn’t need to be in the VirtualTeams repo.  Make sense?

**Comment by amoralesg001** [comment]
Yes, that would make a lot more sense. Ill just delete this issue then.
