### ISSUE TITLE
(Repost of Elaine's issue on Labora) Review Book Chapter 18: Flow Theory and Research 

### ISSUE THREAD

**Issue by amoralesg001** [Collegeville/VirtualTeams#14]
Elaine: 
" This book chapter from the Oxford Handbook of Positive Psychology was authored by Nakamura and Csikszentmihalyi. Next time we meet, let's talk about question 2 at the end of the chapter as it pertains to software teams who are remotely working.

Citation:
Nakamura, J. & Csikszentmihalyi, M. (2009). Flow Theory and Research. Oxford Handbook of Positive Psychology, (Eds) C. R. Snyder, Shane J. Lopez, 195-206. "

**Comment by elaineraybourn** [comment]
👽
