### ISSUE TITLE
(Repost of Elaine's Issue on Labora) Review article: The importance of flow in software development

### ISSUE THREAD

**Issue by amoralesg001** [Collegeville/VirtualTeams#15]
Elaine: 
"Csikszentmihalyi's concept of flow has been applied to happiness and productivity by several. Review this Software & Systems Modeling article discussing the role of flow in software development. The authors argue that software development can be a creative activity. Next time we meet, let's discuss the question, "when might software development be a creative activity and how can we tell?"

Citation:
Gray, J., Rumpe, B. The importance of flow in software development. Softw Syst Model 16, 927–928 (2017). https://doi.org/10.1007/s10270-017-0621-x

Additional resources:
Getting into the Developer Flow State
Flow: The Psychology of Optimal Experience by Mihaly Csikszentmihalyi. Your library may have this text, see the flow model below. "

![Screen Shot 2020-06-26 at 8 50 51 AM](https://user-images.githubusercontent.com/61022265/85864434-24dc2b00-b78a-11ea-8430-0f0a041af698.png)
"

**Comment by elaineraybourn** [comment]
👽
